include(
    ":core",
    ":app",
    ":feature:common_book_info",
    ":feature:settings",
    ":feature:read_book",
    ":feature:books_store",
    ":feature:my_books",
    ":feature:book_details",
    ":widgets:progress_bar"
)